### PR TITLE
 #57 remove useless and non-existant require

### LINKED ISSUE #57: build is broken

### PR DESCRIPTION
**Pull request by MichaelBailly**
Fixes #57

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -11,7 +11,6 @@ require('./app/app.mocks.js');
 // then require everything we need...
 require('esn-frontend-inbox/src/esn.inbox.libs/app/app.module.js');
 require('esn-frontend-inbox/src/linagora.esn.unifiedinbox/app/directives/main.js');
-require('esn-frontend-inbox/src/linagora.esn.unifiedinbox/app/services/mailto-parser/mailto-parser.js');
```
Comment (tuanlc) [inline src/index.js:14]: I surprise why Webpack does not cry on non-existant requirement

**Review by tuanlc — APPROVED** [review]

**Review by rezk2ll — DISMISSED** [review]

**Review by piavgh — DISMISSED** [review]

**Review by rezk2ll — APPROVED** [review]

**Review by tuanlc — APPROVED** [review]
